// Quotes for the Order Success “Victory” screen.
// NOTE: These are user-provided lines. Add more by appending objects.
// Shape: { character: string, en: string, ar: string }

export const orderSuccessQuotes = [
  // Dexter Morgan
  { character: 'Dexter Morgan', en: 'Always be careful what you thank for.', ar: 'كن دائمًا حذرًا مما تشكر عليه.' },
  { character: 'Dexter Morgan', en: 'Darkness can be appreciated even in light.', ar: 'يمكن تقدير الظلام حتى في وجود النور.' },
  { character: 'Dexter Morgan', en: 'Control is everything.', ar: 'التحكّم هو كل شيء.' },
  { character: 'Dexter Morgan', en: 'Order brings peace.', ar: 'النظام يجلب السلام.' },
  { character: 'Dexter Morgan', en: 'Stay precise.', ar: 'ابقَ دقيقًا.' },
  { character: 'Dexter Morgan', en: 'You can enjoy the little things.', ar: 'يمكنك الاستمتاع بالأشياء الصغيرة.' },
  { character: 'Dexter Morgan', en: 'Patience is power.', ar: 'الصبر قوة.' },
  { character: 'Dexter Morgan', en: 'Even in shadows, clarity exists.', ar: 'حتى في الظلال، توجد وضوح.' },
  { character: 'Dexter Morgan', en: 'Focus makes the difference.', ar: 'التركيز يصنع الفارق.' },
  { character: 'Dexter Morgan', en: 'Thanks for keeping it sharp.', ar: 'شكرًا لأنك أبقيت الأمور حادّة.' },

  // Kratos
  { character: 'Kratos', en: 'Strength is earned.', ar: 'القوة تُكتسب.' },
  { character: 'Kratos', en: 'Face your challenges.', ar: 'واجه تحدياتك.' },
  { character: 'Kratos', en: 'Power comes with action.', ar: 'القوة تأتي مع الفعل.' },
  { character: 'Kratos', en: 'Victory favors the bold.', ar: 'النصر يساند الجريئين.' },
  { character: 'Kratos', en: 'Thank you, warrior.', ar: 'شكرًا لك، أيها المحارب.' },
  { character: 'Kratos', en: 'Courage defines you.', ar: 'الشجاعة تُعرّفك.' },
  { character: 'Kratos', en: 'No regrets, only progress.', ar: 'لا ندم، بل تقدّم فقط.' },
  { character: 'Kratos', en: 'Conquer your goals.', ar: 'اقهر أهدافك.' },
  { character: 'Kratos', en: 'Every step counts.', ar: 'كل خطوة لها قيمة.' },
  { character: 'Kratos', en: 'Forge your path.', ar: 'اصنع طريقك.' },

  // Batman
  { character: 'Batman', en: 'The night is yours.', ar: 'الليل لك.' },
  { character: 'Batman', en: 'Stay vigilant.', ar: 'كن يقظًا.' },
  { character: 'Batman', en: 'Justice is appreciated.', ar: 'العدالة محل تقدير.' },
  { character: 'Batman', en: 'Every action matters.', ar: 'كل فعل مهم.' },
  { character: 'Batman', en: 'Thanks for making a difference.', ar: 'شكرًا لأنك صنعت فرقًا.' },
  { character: 'Batman', en: 'Strength through discipline.', ar: 'القوة عبر الانضباط.' },
  { character: 'Batman', en: 'Even small deeds count.', ar: 'حتى الأعمال الصغيرة تُحسب.' },
  { character: 'Batman', en: 'You are extraordinary.', ar: 'أنت استثنائي.' },
  { character: 'Batman', en: 'Darkness reveals the brave.', ar: 'الظلام يكشف الشجعان.' },
  { character: 'Batman', en: 'Keep being heroic.', ar: 'واصل كونك بطلاً.' },

  // Goku
  { character: 'Goku', en: 'Never stop growing.', ar: 'لا تتوقف عن التطوّر.' },
  { character: 'Goku', en: 'Strength is in the heart.', ar: 'القوة في القلب.' },
  { character: 'Goku', en: 'Challenge yourself.', ar: 'تحدَّ نفسك.' },
  { character: 'Goku', en: 'Keep pushing forward.', ar: 'واصل التقدّم.' },
  { character: 'Goku', en: 'Thanks for your energy.', ar: 'شكرًا على طاقتك.' },
  { character: 'Goku', en: 'Power up your day.', ar: 'اشحن يومك بالقوة.' },
  { character: 'Goku', en: 'Every step is progress.', ar: 'كل خطوة هي تقدّم.' },
  { character: 'Goku', en: 'Aim higher.', ar: 'اطمح للأعلى.' },
  { character: 'Goku', en: 'Believe in yourself.', ar: 'آمن بنفسك.' },
  { character: 'Goku', en: 'Keep going beyond limits.', ar: 'واصل تجاوز الحدود.' },

  // Perfect Cell
  { character: 'Perfect Cell', en: 'Perfection is appreciated.', ar: 'الكمال محل تقدير.' },
  { character: 'Perfect Cell', en: 'Thanks for being flawless.', ar: 'شكرًا لكونك بلا عيب.' },
  { character: 'Perfect Cell', en: 'Evolve every day.', ar: 'تطوّر كل يوم.' },
  { character: 'Perfect Cell', en: 'Strive for greatness.', ar: 'اسعَ للعظمة.' },
  { character: 'Perfect Cell', en: 'Even small victories matter.', ar: 'حتى الانتصارات الصغيرة لها قيمة.' },
  { character: 'Perfect Cell', en: 'Power comes with patience.', ar: 'القوة تأتي مع الصبر.' },
  { character: 'Perfect Cell', en: 'Master your moves.', ar: 'أتقن حركاتك.' },
  { character: 'Perfect Cell', en: 'Every step perfects you.', ar: 'كل خطوة تُكمّلك.' },
  { character: 'Perfect Cell', en: 'Thanks for leveling up.', ar: 'شكرًا لأنك ارتقيت بمستواك.' },
  { character: 'Perfect Cell', en: 'Completion feels good.', ar: 'الإكمال شعور رائع.' },

  // Spider-Man
  { character: 'Spider-Man', en: 'With great purchases comes great joy.', ar: 'مع المشتريات العظيمة تأتي فرحة عظيمة.' },
  { character: 'Spider-Man', en: 'Thanks for swinging by.', ar: 'شكرًا لمرورك السريع.' },
  { character: 'Spider-Man', en: 'Your choices matter.', ar: 'اختياراتك مهمة.' },
  { character: 'Spider-Man', en: 'Every action counts.', ar: 'كل فعل يُحسب.' },
  { character: 'Spider-Man', en: 'Stay amazing.', ar: 'ابقَ رائعًا.' },
  { character: 'Spider-Man', en: 'Web your way to success.', ar: 'انسج طريقك نحو النجاح.' },
  { character: 'Spider-Man', en: 'You’re a hero today.', ar: 'أنت بطل اليوم.' },
  { character: 'Spider-Man', en: 'Adventure awaits.', ar: 'المغامرة بانتظارك.' },
  { character: 'Spider-Man', en: 'Keep moving forward.', ar: 'واصل التقدّم.' },
  { character: 'Spider-Man', en: 'Thanks for being spectacular.', ar: 'شكرًا لكونك مدهشًا.' },

  // Superman
  { character: 'Superman', en: 'Thanks for your heroics.', ar: 'شكرًا على بطولتك.' },
  { character: 'Superman', en: 'Truth and justice prevail.', ar: 'الحقيقة والعدالة تنتصران.' },
  { character: 'Superman', en: 'Strength lies in giving.', ar: 'القوة تكمن في العطاء.' },
  { character: 'Superman', en: 'Every choice matters.', ar: 'كل اختيار مهم.' },
  { character: 'Superman', en: 'You make a difference.', ar: 'أنت تصنع فرقًا.' },
  { character: 'Superman', en: 'Hope is powerful.', ar: 'الأمل قوة.' },
  { character: 'Superman', en: 'Thanks for soaring high.', ar: 'شكرًا لتحليقك عاليًا.' },
  { character: 'Superman', en: 'Your impact is super.', ar: 'أثرك خارق.' },
  { character: 'Superman', en: 'Every day counts.', ar: 'كل يوم له قيمة.' },
  { character: 'Superman', en: 'Keep shining bright.', ar: 'واصل الإشراق.' },

  // Ezio
  { character: 'Ezio Auditore', en: 'Stay sharp.', ar: 'ابقَ يقظًا.' },
  { character: 'Ezio Auditore', en: 'Thanks for your precision.', ar: 'شكرًا لدقّتك.' },
  { character: 'Ezio Auditore', en: 'Every action leaves a mark.', ar: 'كل فعل يترك أثرًا.' },
  { character: 'Ezio Auditore', en: 'Patience leads to success.', ar: 'الصبر يقود إلى النجاح.' },
  { character: 'Ezio Auditore', en: 'Honor your choices.', ar: 'اصنَع قراراتك بشرف.' },
  { character: 'Ezio Auditore', en: 'Seize your moment.', ar: 'اغتنم لحظتك.' },
  { character: 'Ezio Auditore', en: 'Wisdom guides you.', ar: 'الحكمة تهديك.' },
  { character: 'Ezio Auditore', en: 'Every step is meaningful.', ar: 'كل خطوة ذات معنى.' },
  { character: 'Ezio Auditore', en: 'Thank you for your trust.', ar: 'شكرًا لثقتك.' },
  { character: 'Ezio Auditore', en: 'Move with purpose.', ar: 'تحرّك بهدف.' },

  // Napoleon
  { character: 'Napoleon Bonaparte', en: 'Thanks for making bold moves.', ar: 'شكرًا لقيامك بخطوات جريئة.' },
  { character: 'Napoleon Bonaparte', en: 'Victory favors action.', ar: 'النصر يفضّل الفعل.' },
  { character: 'Napoleon Bonaparte', en: 'Every step counts.', ar: 'كل خطوة لها قيمة.' },
  { character: 'Napoleon Bonaparte', en: 'Your choices matter.', ar: 'اختياراتك مهمة.' },
  { character: 'Napoleon Bonaparte', en: 'Conquer your day.', ar: 'اقهر يومك.' },
  { character: 'Napoleon Bonaparte', en: 'Strategy leads to success.', ar: 'الاستراتيجية تقود إلى النجاح.' },
  { character: 'Napoleon Bonaparte', en: 'Thanks for your courage.', ar: 'شكرًا لشجاعتك.' },
  { character: 'Napoleon Bonaparte', en: 'Small wins matter.', ar: 'الانتصارات الصغيرة مهمة.' },
  { character: 'Napoleon Bonaparte', en: 'Aim high.', ar: 'اطمح عاليًا.' },
  { character: 'Napoleon Bonaparte', en: 'Progress is power.', ar: 'التقدّم قوة.' },

  // Alexander the Great
  { character: 'Alexander the Great', en: 'Thanks for greatness.', ar: 'شكرًا على العظمة.' },
  { character: 'Alexander the Great', en: 'Expand your horizons.', ar: 'وسّع آفاقك.' },
  { character: 'Alexander the Great', en: 'Every step is progress.', ar: 'كل خطوة هي تقدّم.' },
  { character: 'Alexander the Great', en: 'Courage changes worlds.', ar: 'الشجاعة تغيّر العوالم.' },
  { character: 'Alexander the Great', en: 'Your journey matters.', ar: 'رحلتك مهمة.' },
  { character: 'Alexander the Great', en: 'Conquer your goals.', ar: 'اقهر أهدافك.' },
  { character: 'Alexander the Great', en: 'Lead with purpose.', ar: 'قد بغاية.' },
  { character: 'Alexander the Great', en: 'Small steps, big victories.', ar: 'خطوات صغيرة، انتصارات كبيرة.' },
  { character: 'Alexander the Great', en: 'Thanks for taking charge.', ar: 'شكرًا لتولّيك القيادة.' },
  { character: 'Alexander the Great', en: 'Achieve more today.', ar: 'حقّق أكثر اليوم.' },

  // Imam Ali (AS)
  { character: 'Imam Ali (AS)', en: 'Knowledge lights the way.', ar: 'العلم ينير الطريق.' },
  { character: 'Imam Ali (AS)', en: 'Patience brings reward.', ar: 'الصبر يجلب الثواب.' },
  { character: 'Imam Ali (AS)', en: 'Your actions matter.', ar: 'أعمالك مهمة.' },
  { character: 'Imam Ali (AS)', en: 'Thanks for your trust.', ar: 'شكرًا لثقتك.' },
  { character: 'Imam Ali (AS)', en: 'Good deeds are remembered.', ar: 'الأعمال الصالحة لا تُنسى.' },
  { character: 'Imam Ali (AS)', en: 'Wisdom guides us.', ar: 'الحكمة ترشدنا.' },
  { character: 'Imam Ali (AS)', en: 'Every step counts.', ar: 'كل خطوة لها قيمة.' },
  { character: 'Imam Ali (AS)', en: 'Be just and kind.', ar: 'كن عادلاً ورحيماً.' },
  { character: 'Imam Ali (AS)', en: 'Gratitude is power.', ar: 'الامتنان قوة.' },
  { character: 'Imam Ali (AS)', en: 'Thanks for doing right.', ar: 'شكرًا لفعل الصواب.' },

  // Imam Hussein (AS)
  { character: 'Imam Hussein (AS)', en: 'Stand for what is right.', ar: 'قِف مع الحق.' },
  { character: 'Imam Hussein (AS)', en: 'Courage is valued.', ar: 'الشجاعة مُقدَّرة.' },
  { character: 'Imam Hussein (AS)', en: 'Your choices matter.', ar: 'اختياراتك مهمة.' },
  { character: 'Imam Hussein (AS)', en: 'Thanks for your loyalty.', ar: 'شكرًا لوفائك.' },
  { character: 'Imam Hussein (AS)', en: 'Truth always shines.', ar: 'الحق دائمًا يضيء.' },
  { character: 'Imam Hussein (AS)', en: 'Perseverance brings honor.', ar: 'الثبات يجلب الشرف.' },
  { character: 'Imam Hussein (AS)', en: 'Every action counts.', ar: 'كل عمل يُحسب.' },
  { character: 'Imam Hussein (AS)', en: 'Do good, receive good.', ar: 'افعل الخير تلقَ الخير.' },
  { character: 'Imam Hussein (AS)', en: 'Thanks for being steadfast.', ar: 'شكرًا لثباتك.' },
  { character: 'Imam Hussein (AS)', en: 'Keep your heart strong.', ar: 'اجعل قلبك قويًا.' },

  // Khalid ibn al-Waleed
  { character: 'Khalid ibn al-Waleed', en: 'Courage is respected.', ar: 'الشجاعة محل احترام.' },
  { character: 'Khalid ibn al-Waleed', en: 'Thanks for taking action.', ar: 'شكرًا لاتخاذك المبادرة.' },
  { character: 'Khalid ibn al-Waleed', en: 'Every step counts.', ar: 'كل خطوة لها قيمة.' },
  { character: 'Khalid ibn al-Waleed', en: 'Your choices are strong.', ar: 'اختياراتك قوية.' },
  { character: 'Khalid ibn al-Waleed', en: 'Persistence leads to success.', ar: 'المثابرة تقود إلى النجاح.' },
  { character: 'Khalid ibn al-Waleed', en: 'Valor is appreciated.', ar: 'البسالة محل تقدير.' },
  { character: 'Khalid ibn al-Waleed', en: 'Thanks for your dedication.', ar: 'شكرًا لتفانيك.' },
  { character: 'Khalid ibn al-Waleed', en: 'Strength lies in resolve.', ar: 'القوة تكمن في العزم.' },
  { character: 'Khalid ibn al-Waleed', en: 'Boldness matters.', ar: 'الجرأة مهمة.' },
  { character: 'Khalid ibn al-Waleed', en: 'Every effort makes a difference.', ar: 'كل جهد يصنع فرقًا.' },

  // Salahuddin
  { character: 'Salahuddin', en: 'Wisdom guides the way.', ar: 'الحكمة تهدي الطريق.' },
  { character: 'Salahuddin', en: 'Thanks for your honor.', ar: 'شكرًا لشرفك.' },
  { character: 'Salahuddin', en: 'Patience wins the day.', ar: 'الصبر يكسب اليوم.' },
  { character: 'Salahuddin', en: 'Every step counts.', ar: 'كل خطوة لها قيمة.' },
  { character: 'Salahuddin', en: 'Your integrity matters.', ar: 'نزاهتك مهمة.' },
  { character: 'Salahuddin', en: 'Kindness is strength.', ar: 'الرحمة قوة.' },
  { character: 'Salahuddin', en: 'Thanks for doing good.', ar: 'شكرًا لفعل الخير.' },
  { character: 'Salahuddin', en: 'Persevere with dignity.', ar: 'اثبت بكرامة.' },
  { character: 'Salahuddin', en: 'Your choices matter.', ar: 'اختياراتك مهمة.' },
  { character: 'Salahuddin', en: 'Every action reflects character.', ar: 'كل فعل يعكس الخُلُق.' },

  // Joel Miller
  { character: 'Joel Miller', en: 'Thanks for surviving.', ar: 'شكرًا لأنك صمدت.' },
  { character: 'Joel Miller', en: 'Keep moving forward.', ar: 'واصل التقدّم.' },
  { character: 'Joel Miller', en: 'Every step counts.', ar: 'كل خطوة لها قيمة.' },
  { character: 'Joel Miller', en: 'Strength is appreciated.', ar: 'القوة محل تقدير.' },
  { character: 'Joel Miller', en: 'Your choices matter.', ar: 'اختياراتك مهمة.' },
  { character: 'Joel Miller', en: 'Stay resilient.', ar: 'ابقَ صامدًا.' },
  { character: 'Joel Miller', en: 'Thanks for sticking around.', ar: 'شكرًا لبقائك معنا.' },
  { character: 'Joel Miller', en: 'Courage changes everything.', ar: 'الشجاعة تغيّر كل شيء.' },
  { character: 'Joel Miller', en: 'Take what you can and move.', ar: 'خذ ما تستطيع وامضِ.' },
  { character: 'Joel Miller', en: 'Every effort is valued.', ar: 'كل جهد مُقدَّر.' },

  // Jon Snow
  { character: 'Jon Snow', en: 'The night is yours.', ar: 'الليل لك.' },
  { character: 'Jon Snow', en: 'Thanks for standing tall.', ar: 'شكرًا لثباتك.' },
  { character: 'Jon Snow', en: 'Courage never goes unnoticed.', ar: 'الشجاعة لا تمرّ دون ملاحظة.' },
  { character: 'Jon Snow', en: 'Every choice matters.', ar: 'كل اختيار مهم.' },
  { character: 'Jon Snow', en: 'Strength comes from loyalty.', ar: 'القوة تأتي من الوفاء.' },
  { character: 'Jon Snow', en: 'Thanks for your bravery.', ar: 'شكرًا لشجاعتك.' },
  { character: 'Jon Snow', en: 'Keep leading the way.', ar: 'واصل قيادة الطريق.' },
  { character: 'Jon Snow', en: 'Honor guides you.', ar: 'الشرف يرشدك.' },
  { character: 'Jon Snow', en: 'Every step counts.', ar: 'كل خطوة لها قيمة.' },
  { character: 'Jon Snow', en: 'Winter is easier together.', ar: 'الشتاء أسهل معًا.' },

  // Jesse Pinkman
  { character: 'Jesse Pinkman', en: 'Yeah, thanks, man!', ar: 'إيه، شكرًا يا رجل!' },
  { character: 'Jesse Pinkman', en: 'Every move counts.', ar: 'كل حركة تُحسب.' },
  { character: 'Jesse Pinkman', en: 'Keep it real.', ar: 'خلّك على حقيقتك.' },
  { character: 'Jesse Pinkman', en: 'Your choice rocks.', ar: 'اختيارك رهيب.' },
  { character: 'Jesse Pinkman', en: 'Thanks for sticking around.', ar: 'شكرًا لبقائك معنا.' },
  { character: 'Jesse Pinkman', en: 'You made it awesome.', ar: 'خلّيتها رهيبة.' },
  { character: 'Jesse Pinkman', en: 'Stay chill.', ar: 'ابقَ هادئًا.' },
  { character: 'Jesse Pinkman', en: 'Every little thing matters.', ar: 'كل شيء صغير مهم.' },
  { character: 'Jesse Pinkman', en: 'Thanks for the support.', ar: 'شكرًا على الدعم.' },
  { character: 'Jesse Pinkman', en: 'You’re the real deal.', ar: 'أنت الحقيقي.' },

  // Walter White
  { character: 'Walter White', en: 'Thanks for your precision.', ar: 'شكرًا لدقّتك.' },
  { character: 'Walter White', en: 'Every choice builds power.', ar: 'كل اختيار يبني قوة.' },
  { character: 'Walter White', en: 'Your effort is valued.', ar: 'جهدك مُقدَّر.' },
  { character: 'Walter White', en: 'Master your craft.', ar: 'أتقن صنعتك.' },
  { character: 'Walter White', en: 'Thanks for taking control.', ar: 'شكرًا لتولّيك زمام الأمور.' },
  { character: 'Walter White', en: 'Focus brings success.', ar: 'التركيز يجلب النجاح.' },
  { character: 'Walter White', en: 'Every step counts.', ar: 'كل خطوة لها قيمة.' },
  { character: 'Walter White', en: 'Knowledge is power.', ar: 'المعرفة قوة.' },
  { character: 'Walter White', en: 'Thanks for being smart.', ar: 'شكرًا لكونك ذكيًا.' },
  { character: 'Walter White', en: 'Your impact is real.', ar: 'أثرك حقيقي.' },
];
